ProjectEWS/Controllers/CoordinatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjectEWS.Entity;
using ProjectEWS.Filter;

namespace ProjectEWS.Controllers
{
    public class CoordinatorController : Controller
    {
        DataContext dbc =new DataContext();
        // GET: Coordinator
        public ActionResult Login(string ReturnUrl, string Message)
        {
            if (ReturnUrl != null && Message != null)
            {
                ViewBag.ReturnUrl = ReturnUrl;
                ViewBag.Message = Message;
            }
            return View();
        }
        [HttpPost]
        public ActionResult Login(string Username, string Password, string ReturnUrl)
        {
            var model = dbc.Coordinators.AsNoTracking().SingleOrDefault(a => a.UserName == Username && a.Pass == Password);
            if (model != null)
            {
                Session["Cordinator"] = model;
                ViewBag.Message = "Login Succesfully";
                if (ReturnUrl != "")
                {
                    return Redirect(ReturnUrl);
                }
            }
            else
            {
                ViewBag.Message = "Login Failed";
            }

            return View();
        }
        [Coordinator()]
        public ActionResult MagazineByCordinator()
        {
            var cor = Session["Cordinator"] as Coordinator;
            
            if (cor != null)
            {
                var model = dbc.Coordinators.Find(cor.Id);
                if (model != null)
                {
                    var list = model.Students.ToList();
                    
                    
                    return View(list);
                }
            }
            
            return View();
        }
        public ActionResult Logout()
        {
            HttpContext.Session.Remove("Cordinator");
            return RedirectToAction("Login");
        }
    }
}

ProjectEWS/Controllers/MangerController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjectEWS.Entity;
using ProjectEWS.Filter;

namespace ProjectEWS.Controllers
{
    [Author(PermissionNames = "Manager")]
    public class MangerController : Controller
    {
        DataContext dbc =new DataContext();
        // GET: Manger
        public ActionResult Index()
        {
            var model = dbc.Magazines.AsNoTracking().ToList();
            return View(model);
        }

        [HttpPost]
        public ActionResult Zip()
        {
            var model = dbc.Magazines.AsNoTracking().ToList();
            ViewBag.Message = "Your contact page.";
            try
            {
                string path = Server.MapPath("~/images/products/");
                string archive_path = Server.MapPath("~/Archived/");
                if (!Directory.Exists(archive_path))
                {
                    Directory.CreateDirectory(archive_path);
                }

                var url =  "uploaded_" + DateTime.Now.Day.ToString() + DateTime.Now.Minute.ToString() +
                          DateTime.Now.Second.ToString() + ".zip";
                ViewBag.url = url;
                System.IO.Compression.ZipFile.CreateFromDirectory(path,archive_path+ url);
            }
            catch { }
            return View("Index", model);
        }
        public ActionResult DownloadFile(String url)
        {
            string filename = url;
            string filepath = AppDomain.CurrentDomain.BaseDirectory + "/Archived/" + filename;
            byte[] filedata = System.IO.File.ReadAllBytes(filepath);
            string contentType = MimeMapping.GetMimeMapping(filepath);

            var cd = new System.Net.Mime.ContentDisposition
            {
                FileName = filename,
                Inline = true,
            };

            Response.AppendHeader("Content-Disposition", cd.ToString());

            return File(filedata, contentType);
        }
    }
}

ProjectEWS/Controllers/MegazineController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjectEWS.Entity;
using ProjectEWS.Filter;
using ProjectEWS.Utils;

namespace ProjectEWS.Controllers
{
    public class MegazineController : Controller
    {
        DataContext dbc =new DataContext();
        // GET: Megazine
        [Student()]
        public ActionResult Index()
        {
            ViewBag.SemesterId = new SelectList(dbc.Semesters, "Id", "Name");
            Magazine magazine=new Magazine();
            magazine.SentDate=DateTime.Now;
            return View(magazine);
        }
        [HttpPost]
        public ActionResult Index(HttpPostedFileBase ImageUpload,string Comment,DateTime SentDate,int SemesterId,bool Agree)
        {
            ViewBag.SemesterId = new SelectList(dbc.Semesters, "Id", "Name");
            Magazine magazine2 = new Magazine();
            magazine2.SentDate = DateTime.Now;
            var message = "";
            var url = "";
            var studentId = Session["Student"] as Student;
            if (ImageUpload!=null)
            {
                url = Guid.NewGuid() + ImageUpload.FileName.Substring(ImageUpload.FileName.LastIndexOf("."));
                ImageUpload.SaveAs(Server.MapPath("~/images/products/" + url));
            }
            else
            {
                url = "Product.png";
            }
            Magazine magazine=new Magazine
            {
                Comment = Comment,
                SemesterId = SemesterId,
                SentDate = SentDate,
                StudentId = studentId.Id,
                 Url = url
            };
            try
            {
                var seme = dbc.Semesters.Find(SemesterId);
                var moderator = dbc.Students.AsNoTracking().SingleOrDefault(a => a.Id == studentId.Id);
                var deadlin = seme.EndDate;
                if (seme != null)
                {
                    if (Agree == true)
                    {
                        if (DateTime.Compare(SentDate, deadlin) > 0)
                        {
                            
                                message = "Hết hạn gửi bài";
                        }
                        else
                        {
                            dbc.Magazines.Add(magazine);
                            dbc.SaveChanges();
                            var cordinator = moderator.Coordinator.Email;
                            XMailer.Send(cordinator, "Notication", "Student"+studentId.FullName+"Have upload new record ");
                            message = "Submit Successfully";
                        }
                    }
                    else
                    {
                        message = "You have to agree with our policy";
                    }
                }
                
                ViewBag.message = message;
            }
            catch (Exception) { }
            return View(magazine2);
        }
    }
}

ProjectEWS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container">
        <header class="nn-header row">
            <div class="nn-company">
                <h1>Online shopping mall</h1>
                <h5>The center point of the professional programming</h5>
            </div>
            <img class="pull-right" src="/images/header-object.png" />
        </header>
        @Html.Partial("_Menu")


        <div class="nn-sheet row">

            <article class="col-sm-12">
                <div class="nn-body">
                    @RenderBody()
                </div>
            </article>


        </div>

        <footer class="panel panel-default row">
            <div class="panel-heading">
                <p class="text-center">Student Megazine 2019.</p>
            </div>
        </footer>
    </div>


    @Scripts.Render("~/bundles/jquery")
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ProjectEWS/Views/Shared/_Menu.cshtml
<div class="navbar navbar-inverse row">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>
    <div class="navbar-collapse collapse">
        <!--Menu-->
        <ul class="nav navbar-nav">
            <li>@Html.ActionLink("Home", "Index", "Home")</li>


            <li>@Html.ActionLink("Student Register", "Register", "Student")</li>

            <li>@Html.ActionLink("Magazine", "Index", "Megazine")</li>
            <li>@Html.ActionLink("MagazineByCordinator", "MagazineByCordinator", "Coordinator")</li>
@*            <li>@Html.ActionLink("Report", "Index", "Report")</li>*@
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span> Report <span class="caret"></span></a>
                <ul class="dropdown-menu">


                    <li><a href="/Report/Index">General</a></li>
                    <li><a href="/Report/Index2">ByCourse</a></li>
                    <li><a href="/Report/Index3">ByStudent</a></li>
                    
                </ul>
            </li>
            <li>@Html.ActionLink("General Manager", "Index", "Manger")</li>
            @{
                if (Session["User"] != null)
                {
                    <li>@Html.ActionLink("Manger", "Index", "Manger")</li>
                    <li>@Html.ActionLink("Logout", "Logout", "Admin")</li>
                }


            }
            @{
                if (Session["Student"] != null)
                {

                    <li>@Html.ActionLink("Logout", "Logout", "Student")</li>
                }

            }
            @{
                if (Session["Cordinator"] != null)
                {

                    <li>@Html.ActionLink("Logout", "Logout", "Coordinator")</li>
                }

            }
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span> Admin <span class="caret"></span></a>
                <ul class="dropdown-menu">


                    <li><a href="/CourseManager/Index">Course</a></li>
                    <li><a href="/SemesterManager/Index">Semester</a></li>
                    <li><a href="/StudentManager/Index">Student</a></li>
                    <li><a href="/MegazineManager/Index">Megazine</a></li>
                    <li><a href="/MasterManager/Index">Master</a></li>
                    <li><a href="/RoleManager/Index">Role</a></li>
                    <li><a href="/MasterRoleManager/Index">Role Distribution</a></li>
                </ul>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="#" data-lang="en">English</a></li>
            <li><a href="#" data-lang="vi">VietNamese</a></li>
        </ul>
        <!--Menu-->
    </div>
</div>